config/routes.rb
Rails.application.routes.draw do
  root 'session#index'

  
  get "log_in" => "session#new", :as => "log_in"
  get "/explanation" => "session#explanation"
  post "log_in" => "session#create"
  get "log_out" => "session#destroy"
  get "/help" => "session#help"

  get "/feedback" => "feedback#feedback"
  post "/feedback" => "feedback#feedback_sent"

  get "/members/new" => "members#new", :as => "new_member"
  post "/members" => "members#create", :as => "create_member"
  get "/members" => "members#index", :as => "members"
  get "/member/:id" => "members#show", :as => "member"
  get "/members/edit/:id" => "members#edit"
  put '/member/:id' => "members#update", :as => 'update_member'
  delete '/members/delete/:id' => "members#destroy"

  get "/junior_enterprises/new" => "junior_enterprises#new", :as => "new_junior_enterprise"
  get "/messages" => "junior_enterprises#messages"
  post "/junior_enterprises" => "junior_enterprises#create", :as => "create_junior_enterprise"
  get "/junior_enterprises/edit" => "junior_enterprises#edit", :as => "edit_junior_enterprise"
  put "/junior_enterprises/:id" => "junior_enterprises#update", :as => "update_junior_enterprise"
  get "/junior_enterprises" => "junior_enterprises#index", :as => "junior_enterprises"
  get "/junior_enterprise/:id" => "junior_enterprises#show", :as => "junior_enterprise"
  get "/dashboard" => "junior_enterprises#dashboard", :as => "dashboard"
  get "/find" => "junior_enterprises#find", :as => "find"
  get "/search" => "junior_enterprises#search", :as => "search"
  get "/junior_enterprises/:id/seal" => "junior_enterprises#seal"

  get '/admin/junior_enterprises' => "junior_enterprises#index"
  get '/admin/junior_enterprises/edit/:id' => "junior_enterprises#edit"
  get '/admin/junior_enterprises/new' => "junior_enterprises#new"
  get '/admin/junior_enterprises/delete/:id' => "junior_enterprises#destroy"  
  patch "/junior_enterprise/:id" => "junior_enterprises#update"

  get '/admin/messages' => "messages#index"
  get '/admin/messages/edit/:id' => "messages#edit"
  get '/admin/messages/new' => "messages#new"
  post '/messages/:id' => "messages#create"
  post '/messages' => "messages#create"
  delete '/messages/:id' => "messages#destroy"
  get '/admin/messages/delete/:id' => "messages#destroy"  
  put "/admin/message/:id" => "messages#update", :as => "update_message"

  get '/admin/users' => "users#index", :as => 'admin_users'
  get '/admin/users/edit/:id' => "users#edit"
  get '/admin/users/new' => "users#new"
  get '/admin/users/delete/:id' => "users#destroy"

  get '/admin/members' => "members#index"
  get '/admin/members/edit/:id' => "members#edit"
  get '/admin/members/new' => "members#new"
  get '/admin/members/delete/:id' => "members#destroy"

  get '/federation/dashboard' => "junior_enterprises#search"

  get "/users/new" => "users#new", :as => "new_user"
  post "/users" => "users#create", :as => "create_user"
  get "/users" => "users#index", :as => "users"
  get "/user/:id" => "users#show", :as => "user"
  get "/recover" => "users#recover", :as => "recover"  
  post "/recover" => "users#recover_email"
  put '/users/:id' => "users#update", :as => 'update_user'

end

app/views/admin/junior_enterprise_edit.html.erb
<%= render 'layouts/adminheadmenu' %>
<div id="layout-container">
  <div id="main">  
    <div class="head-title">
    </div>
    <div class="menu-switch">
      <i class="fa fa-bars"></i>
    </div>
    <div class="row">
      <div class="col-md-12"></div>
    </div>
    <div class="margin-container">
    <div class="scrollable wrapper">
      <div class="row">
        <div class="col-md-12">
          <div class="page-heading">
            <h1><b>Editar Empresa Junior</b></h1>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-9">
          <div class="box-info">
            <table align="center" border="0" cellpadding="0" cellspacing="0">
              <tbody>
              <tr>
                <td>
                  <div>
                    <div id="wizard" class="swMain">
                        <%= form_for @junior_enterprise, url: update_junior_enterprise_path(@junior_enterprise.id), :html => { :method => :put }  do |f| %>
                          <% if @junior_enterprise.errors.any? %>    
                              <% @junior_enterprise.errors.full_messages.each do |msg| %>
                                <div class= "alert alert-danger">
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= msg %>
                                </div>
                              <% end %>    
                          <% end %>
                          <% flash.each do |name, msg| %>      
                            <% if msg.is_a?(String) %>
                              <% if flash[:error] -%>
                                <div class="alert alert-danger" >
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                                </div>
                              <% end %>

                              <% if flash[:alert] -%>
                                <div class="alert alert-warning" >
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                                </div>
                              <% end %>

                              <% if flash[:notice] -%>
                                <div class="alert alert-success" >
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                                </div>
                              <% end %>
                            <% end %>
                          <% end %>

                          <ul class="anchor">
                            <li>
                              <a class="selected">
                                <span class="stepDesc">Dados<br></span>
                              </a>
                            </li>
                          </ul>
                          <div id="step-1" style="display: block; left: 0px;">
                            <table cellspacing="3" cellpadding="3" align="center">
                              <tbody>
                                <tr>
                                  <td align="center" colspan="3">&nbsp;</td>
                                </tr>
                                <tr>
                                  <td align="right">Nome</td>
                                  <td align="left">
                                    <%= f.text_field :name, class: "txtBox", placeholder: "Nome"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Slogan</td>
                                  <td align="left">
                                    <%= f.text_field :phrase, class: "txtBox", placeholder: "Frase"  %>
                                  </td>
                                </tr>                                
                                <tr>
                                  <td align="right">Descrição</td>
                                  <td align="left">
                                    <%= f.text_field(:description, class: "txtBox", placeholder: "Descrição", size: 20)  %>
                                  </td>
                                </tr>                                
                                <tr>
                                  <td align="right">Curso</td>
                                  <td align="left">
                                    <%= f.text_field(:course, class: "txtBox", placeholder: "Curso", size: 20)  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Área de Atuação :</td>
                                  <td align="left">                                    
                                    <%= select_tag('junior_enterprise[area]', options_for_select([['Em Construção']], selected: @junior_enterprise.area )) %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Tipo de Serviço:</td>
                                  <td align="left">
                                      <%= f.check_box :project, style:"margin-left:5px"%> Projetos
                                      <%= f.check_box :consultor, style:"margin-left:5px"%> Consultoria
                                      <%= f.check_box :training, style:"margin-left:5px"%> Treinamento
                                      <%= f.check_box :product, style:"margin-left:5px"%> Produtos
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Site</td>
                                  <td align="left">
                                    <%= f.text_field :site, class: "txtBox", placeholder: "Site"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Telefone</td>
                                  <td align="left">
                                    <%= f.text_field :phone, class: "txtBox", placeholder: "Telefone"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Facebook</td>
                                  <td align="left">
                                    <%= f.text_field :facebook, class: "txtBox", placeholder: "Facebook"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Youtube</td>
                                  <td align="left">
                                    <%= f.text_field :youtube, class: "txtBox", placeholder: "Youtube"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Estado</td>
                                  <td align="left">                                    
                                    <%= select_tag('junior_enterprise[state]', options_for_select([['Acre'],['Alagoas'], ['Amapá'], ['Amazonas'], ['Bahia'], ['Ceará'], ['Distrito Federal'], ['Espirito Santo'], ['Goiás'], ['Maranhão'], ['Mato Grosso'], ['Mato Grosso do Sul'], ['Minas Gerais'], ['Pará'], ['Paraíba'], ['Paraná'], ['Pernambuco'], ['Piauí'], ['Rio de Janeiro'], ['Rio Grande do Norte'], ['Rio Grande do Sul'], ['Rondônia'], ['Roraima'], ['Santa Catarina'], ['São Paulo'], ['Sergipe'], ['Tocantins']], selected: @junior_enterprise.state )) %>
                                  </td>
                                </tr>                                
                                <tr>
                                  <td align="right">Cidade</td>
                                  <td align="left">
                                    <%= f.text_field :city, class: "txtBox", placeholder: "Cidade"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Endereço :</td>
                                  <td align="left">
                                    <%= f.text_field :address, class: "txtBox", placeholder: "Endereço, Rua e Numero"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Logo</td>
                                  <td align="left">
                                    <%= f.file_field :logo, class: "txtBox" %>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                          <br>
                          <div class="stepContainer" style="height: 179px;"></div>
                          <div class="actionBar">
                            <%= submit_tag "Editar",:class=> 'buttonFinish'%>
                          </div>
                        <% end %>                        
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    </div>
</div>

app/views/admin/member_edit.html.erb
<%= render 'layouts/adminheadmenu' %>
<div id="layout-container">
  <div id="main">  
    <div class="head-title">
    </div>
    <div class="menu-switch">
      <i class="fa fa-bars"></i>
    </div>
    <div class="row">
      <div class="col-md-12"></div>
    </div>
    <div class="margin-container">
    <div class="scrollable wrapper">
      <div class="row">
        <div class="col-md-12">
          <div class="page-heading">
            <h1><b>Editar Membro</b></h1>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-9">
          <div class="box-info">
            <table align="center" border="0" cellpadding="0" cellspacing="0">
              <tbody>
              <tr>
                <td>
                  <div>
                    <div id="wizard" class="swMain">
                        <%= form_for @member, url: update_member_path(@member.id), :html => { :method => :put }  do |f| %>
                          <% if @member.errors.any? %>    
                              <% @member.errors.full_messages.each do |msg| %>
                                <div class= "alert alert-danger">
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= msg %>
                                </div>
                              <% end %>    
                          <% end %>
                          <% flash.each do |name, msg| %>      
                            <% if msg.is_a?(String) %>
                              <% if flash[:error] -%>
                                <div class="alert alert-danger" >
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                                </div>
                              <% end %>

                              <% if flash[:alert] -%>
                                <div class="alert alert-warning" >
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                                </div>
                              <% end %>

                              <% if flash[:notice] -%>
                                <div class="alert alert-success" >
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                                </div>
                              <% end %>
                            <% end %>
                          <% end %>

                          <ul class="anchor">
                            <li>
                              <a class="selected">
                                <span class="stepDesc">Dados<br></span>
                              </a>
                            </li>
                          </ul>
                          <div id="step-1" style="display: block; left: 0px;">
                            <table cellspacing="3" cellpadding="3" align="center">
                              <tbody>
                                <tr>
                                  <td align="center" colspan="3">&nbsp;</td>
                                </tr>
                                <tr>
                                  <td align="right">Nome</td>
                                  <td align="left">
                                    <%= f.text_field :name, class: "txtBox", placeholder: "Nome"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Cargo</td>
                                  <td align="left">
                                    <%= f.text_field :position, class: "txtBox", placeholder: "Cargo"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Telefone</td>
                                  <td align="left">
                                    <%= f.text_field :phone, class: "txtBox", placeholder: "Telefone"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">E-mail</td>
                                  <td align="left">
                                    <%= f.text_field :email, class: "txtBox", placeholder: "E-mail"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Empresa Junior</td>
                                  <td align="left">
                                    <%= select_tag "member[junior_enterprise_id]", options_from_collection_for_select(@junior_enterprises, "id", "name"), class: 'form-control' %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Foto</td>
                                  <td align="left">
                                    <%= f.file_field :photo, class: "txtBox" %>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                          <br>
                          <div class="stepContainer" style="height: 179px;"></div>
                          <div class="actionBar">
                            <%= submit_tag "Editar",:class=> 'buttonFinish', :method=> :patch %>
                          </div>
                        <% end %>                        
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    </div>
</div>
<script>
  $("#member_email").inputmask({ alias: "email"});
  $("#member_phone").inputmask("(99)9999-9999");
</script>

app/views/admin/message_edit.html.erb
<%= render 'layouts/adminheadmenu' %>
<div id="layout-container">
  <div id="main">  
    <div class="head-title">
    </div>
    <div class="menu-switch">
      <i class="fa fa-bars"></i>
    </div>
    <div class="row">
      <div class="col-md-12"></div>
    </div>
    <div class="margin-container">
    <div class="scrollable wrapper">
      <div class="row">
        <div class="col-md-12">
          <div class="page-heading">
            <h1><b>Editar Mensagem</b></h1>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-9">
          <div class="box-info">
            <table align="center" border="0" cellpadding="0" cellspacing="0">
              <tbody>
              <tr>
                <td>
                  <div>
                    <div id="wizard" class="swMain">
                        <%= form_for @message, url: update_message_path(@message.id), :html => { :method => :put }  do |f| %>
                          <% if @message.errors.any? %>    
                              <% @message.errors.full_messages.each do |msg| %>
                                <div class= "alert alert-danger">
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= msg %>
                                </div>
                              <% end %>    
                          <% end %>
                          <% flash.each do |name, msg| %>      
                            <% if msg.is_a?(String) %>
                              <% if flash[:error] -%>
                                <div class="alert alert-danger" >
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                                </div>
                              <% end %>

                              <% if flash[:alert] -%>
                                <div class="alert alert-warning" >
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                                </div>
                              <% end %>

                              <% if flash[:notice] -%>
                                <div class="alert alert-success" >
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                                </div>
                              <% end %>
                            <% end %>
                          <% end %>

                          <ul class="anchor">
                            <li>
                              <a class="selected">
                                <span class="stepDesc">Dados<br></span>
                              </a>
                            </li>
                          </ul>
                          <div id="step-1" style="display: block; left: 0px;">
                            <table cellspacing="3" cellpadding="3" align="center">
                              <tbody>
                                <tr>
                                  <td align="center" colspan="3">&nbsp;</td>
                                </tr>
                                <tr>
                                  <td align="right">Nome</td>
                                  <td align="left">
                                    <%= f.text_field :name, class: "txtBox", placeholder: "Nome"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">E-mail</td>
                                  <td align="left">
                                    <%= f.text_field :email, class: "txtBox", placeholder: "E-mail"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Telefone</td>
                                  <td align="left">
                                    <%= f.text_field :phone, class: "txtBox", placeholder: "Telefone"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Texto</td>
                                  <td align="left">
                                    <%= f.text_area :text, class: "txtBox", placeholder: "Telefone", rows: 10, cols: 30  %>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                          <br>
                          <div class="stepContainer" style="height: 179px;"></div>
                          <div class="actionBar">
                            <%= submit_tag "Editar",:class=> 'buttonFinish', :method=> :patch %>
                          </div>
                        <% end %>                        
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    </div>
</div>
<script>
  $("#message_email").inputmask({ alias: "email"});
  $("#message_phone").inputmask("(99)9999-9999");
</script>

app/views/admin/user_edit.html.erb
<%= render 'layouts/adminheadmenu' %>
<div id="layout-container">
  <div id="main">  
    <div class="head-title">
    </div>
    <div class="menu-switch">
      <i class="fa fa-bars"></i>
    </div>
    <div class="row">
      <div class="col-md-12"></div>
    </div>
    <div class="margin-container">
    <div class="scrollable wrapper">
      <div class="row">
        <div class="col-md-12">
          <div class="page-heading">
            <h1><b>Editar Usuário</b></h1>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-9">
          <div class="box-info">
            <table align="center" border="0" cellpadding="0" cellspacing="0">
              <tbody>
              <tr>
                <td>
                  <div>
                    <div id="wizard" class="swMain">
                        <%= form_for @user, url: update_user_path(@user.id), :html => { :method => :put }  do |f| %>
                          <% if @user.errors.any? %>    
                              <% @user.errors.full_messages.each do |msg| %>
                                <div class= "alert alert-danger">
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= msg %>
                                </div>
                              <% end %>    
                          <% end %>
                          <% flash.each do |name, msg| %>      
                            <% if msg.is_a?(String) %>
                              <% if flash[:error] -%>
                                <div class="alert alert-danger" >
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                                </div>
                              <% end %>

                              <% if flash[:alert] -%>
                                <div class="alert alert-warning" >
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                                </div>
                              <% end %>

                              <% if flash[:notice] -%>
                                <div class="alert alert-success" >
                                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                  <%= content_tag :div, msg, :id => "flash_#{name}" %>
                                </div>
                              <% end %>
                            <% end %>
                          <% end %>

                          <ul class="anchor">
                            <li>
                              <a class="selected">
                                <span class="stepDesc">Dados<br></span>
                              </a>
                            </li>
                          </ul>
                          <div id="step-1" style="display: block; left: 0px;">
                            <table cellspacing="3" cellpadding="3" align="center">
                              <tbody>
                                <tr>
                                  <td align="center" colspan="3">&nbsp;</td>
                                </tr>
                                <tr>
                                  <td align="right">E-mail</td>
                                  <td align="left">
                                    <%= f.text_field :email, class: "txtBox", placeholder: "E-mail"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Senha</td>
                                  <td align="left">
                                    <%= f.text_field :password, class: "txtBox", placeholder: "Senha"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Tipo</td>
                                  <td align="left">
                                    <%= select_tag "function", "<option value='user'>Usuário</option><option value='admin'>Administrador</option>".html_safe, class: 'form-control' %>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                          <br>
                          <div class="stepContainer" style="height: 179px;"></div>
                          <div class="actionBar">
                            <%= submit_tag "Editar",:class=> 'buttonFinish'%>
                          </div>
                        <% end %>                        
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    </div>
</div>
<script>
  $("#user_email").inputmask({ alias: "email"});
</script>