config/routes.rb
Rails.application.routes.draw do
  root 'session#index'

  
  get "log_in" => "session#new", :as => "log_in"
  get "/explanation" => "session#explanation"
  post "log_in" => "session#create"
  get "log_out" => "session#destroy"
  get "/help" => "session#help"

  get "/feedback" => "feedback#feedback"
  post "/feedback" => "feedback#feedback_sent"

  get "/members/new" => "members#new", :as => "new_member"
  post "/members" => "members#create", :as => "create_member"
  get "/members" => "members#index", :as => "members"
  get "/member/:id" => "members#show", :as => "member"
  get "/members/edit/:id" => "members#edit"
  put '/member/:id' => "members#update", :as => 'update_member'
  delete '/members/delete/:id' => "members#destroy"

  get "/junior_enterprises/new" => "junior_enterprises#new", :as => "new_junior_enterprise"
  get "/messages" => "junior_enterprises#messages"
  post "/junior_enterprises" => "junior_enterprises#create", :as => "create_junior_enterprise"
  get "/junior_enterprises/edit" => "junior_enterprises#edit", :as => "edit_junior_enterprise"
  put "/junior_enterprises/:id" => "junior_enterprises#update", :as => "update_junior_enterprise"
  get "/junior_enterprises" => "junior_enterprises#index", :as => "junior_enterprises"
  get "/junior_enterprise/:id" => "junior_enterprises#show", :as => "junior_enterprise"
  get "/dashboard" => "junior_enterprises#dashboard", :as => "dashboard"
  get "/find" => "junior_enterprises#find", :as => "find"
  get "/search" => "junior_enterprises#search", :as => "search"
  get "/junior_enterprises/:id/seal" => "junior_enterprises#seal"

  get '/admin/junior_enterprises' => "junior_enterprises#index"
  get '/admin/junior_enterprises/edit/:id' => "junior_enterprises#edit"
  get '/admin/junior_enterprises/new' => "junior_enterprises#new"
  get '/admin/junior_enterprises/delete/:id' => "junior_enterprises#destroy"  
  patch "/junior_enterprise/:id" => "junior_enterprises#update"

  get '/admin/messages' => "messages#index"
  get '/admin/messages/edit/:id' => "messages#edit"
  get '/admin/messages/new' => "messages#new"
  post '/messages/:id' => "messages#create"
  post '/messages' => "messages#create"
  delete '/messages/:id' => "messages#destroy"
  get '/admin/messages/delete/:id' => "messages#destroy"  
  put "/admin/message/:id" => "messages#update", :as => "update_message"

  get '/admin/users' => "users#index", :as => 'admin_users'
  get '/admin/users/edit/:id' => "users#edit"
  get '/admin/users/new' => "users#new"
  get '/admin/users/delete/:id' => "users#destroy"

  get '/admin/members' => "members#index"
  get '/admin/members/edit/:id' => "members#edit"
  get '/admin/members/new' => "members#new"
  get '/admin/members/delete/:id' => "members#destroy"

  get '/federation/dashboard' => "junior_enterprises#search"

  get "/users/new" => "users#new", :as => "new_user"
  post "/users" => "users#create", :as => "create_user"
  get "/users" => "users#index", :as => "users"
  get "/user/:id" => "users#show", :as => "user"
  get "/recover" => "users#recover", :as => "recover"  
  post "/recover" => "users#recover_email"
  put '/users/:id' => "users#update", :as => 'update_user'

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def index
  end	

  def explanation
  end	

  def new
  end

  def help
  end

  def create
    result = HTTParty.get("http://jeapi.herokuapp.com/log_in", 
    :body => { password: params[:password], email: params[:email]},
    :headers => { 'token' => JEAPI_KEY } )


    if result.code != 204
      user = OpenStruct.new(ActiveSupport::JSON.decode(result.body))
      session[:user_id] = user.id
      if is_admin? 
        redirect_to "/admin/users", :notice => "Logged in!"
      elsif is_federation?       
        redirect_to "/federation/dashboard", :notice => "Logged in!"
      else
        redirect_to dashboard_path, :notice => "Logged in!"
      end
    else
      redirect_to "/log_in", :alert => "Password ou Email inválido"     
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged Out!"
  end

end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/explanation.html.erb
<%= stylesheet_link_tag "landingpage" %>
    <%= render 'layouts/minimenu' %>
    <div class="content-section-a" data-scroll-index="0">
        <div class="container">
            <div class="row">
                <div class="col-lg-offset-1 col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix" ></div>
                    <h2 class="section-heading">O que é uma Empresa Junior?</h2>
                    <p class="lead" style="font-size: 16px;">Empresa Junior é uma organização social civil sem fins lucrativos , formada e gerida exclusivamente por alunos de graduação e pós-graduação de ensino superior , que presta serviços para empresas, instituições e da sociedade , sob a orientação de professores e profissionais com o objetivo de consolidar e reforçar a aprendizagem de seus membros. Júnior Empresas são semelhantes a empresas reais , contando com os princípios de governança corporativa como conselho gestor e diretoria além de sua própria regulação.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-1 col-sm-6">
                    <%= image_tag("je.png", style: "width: 300px") %>
                </div>
            </div>
        </div>
    </div>
    <div class="content-section-b">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-push-6  col-sm-6" style="color:#fff">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Por quê contratar uma Empresa Junior?</h2>
                    <p class="lead" style="font-size: 16px;">Por sermos apaixonados pelo que fazemos e sem fins lucrativos.
                        Nós oferecemos serviços profissionais e de alta qualidade a um preço justo.
                        Somos parte de um movimento com pessoas empenhadas a tornar empreendedorismo mais que uma palavra em nosso dicionário, mas sim uma ralidade.</p>
                </div>
                <div class="col-lg-offset-2 col-lg-5 col-sm-pull-6 col-sm-6">
                    <%= image_tag("growth.png", style: "width: 300px") %>
                </div>
            </div>
        </div>
    </div>
    <div class="content-section-a"  data-scroll-index="1">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6 col-lg-offset-1 ">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">O que é a Vitrine?</h2>
                    <p class="lead" style="font-size: 16px">Desenvolvida pela GTi Engenharia Jr, a Vitrine cataloga as empresas juniores brasileiras em um só lugar, possibilitando o acesso à informações e contratação de serviços de forma intuitiva e integrada.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-1 col-sm-6">
                    <%= image_tag("vitrine.png", style: "width: 300px") %>
                </div>
            </div>
        </div>
    </div>
    <div class="banner">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h2>Conecte-se</h2>
                </div>
                <div class="col-lg-12">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="/find" class="btn btn-default btn-lg"><span class="network-name">Encontrar uma Empresa Junior</span></a> OU <a href="/users/new" class="btn btn-default btn-lg"><span class="network-name">Cadastrar uma Empresa Junior</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="list-inline">
                  <li>
                      <a href="/log_in">Log-In</a>
                  </li>
                  <li class="footer-menu-divider">⋅</li>
                  <li>
                      <a href="/feedback">Feedback</a>
                  </li>
                  <li class="footer-menu-divider">⋅</li>
                  <li>
                      <a href="/help">Federações</a>
                  </li>
                    
                </ul>
                <p class="copyright text-muted small">Nerds Cearenses desenvolvendo o MEJ - <a href="http://gti.ufc.br">GTi Engenharia Jr</a></p>
            </div>
        </div>
    </div>
</footer>

<script type="text/javascript">
    $(function(){
        $.scrollIt();
    });
</script>

app/views/session/help.html.erb
<%= render 'layouts/minimenu' %>
<div class="container login-bg">
  <div class="login-form-signin" style="max-width: 500px !important;-webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius: 5px;">
    <div class="login-logo"><%= image_tag("logo.png") %></div>
    <div class="login-wrap">
      
      <h1 style="Margin-top: 0;font-weight: normal;color: #3d88fd;font-family: Ubuntu,sans-serif !important;font-size: 30px;Margin-bottom: 16px;line-height: 44px">
        Seja bem vindo a Vitrine de EJ
      </h1>
      <p style="text-align: left;font-weight: normal;color: #000000;font-family: Ubuntu,sans-serif !important;font-size: 12px;Margin-bottom: 16px">
        Mais abaixo há instruções sobre como sua Federação poderá fazer parte da Vitrine de EJ.
      </p>
            <p>
                <li> Para nos certificar da validade da sua Federação nós precisamos que você envie um e-mail para ...@vitrinedeej.com .</li><br>

                <li> Após isso iremos certificar se o e-mail de sua federação é real, para então cadastramos no sistema.</li><br>

                <li> Então você irá receber um e-mail portando a sua senha e explicando mais sobre o seu cadastro.</li><br>

                <li> A Federação será a unica responsável por validar os Selos EJ, portanto caso sua federação não esteja ativa na Vitrine de EJ não há como validar o Selo das Empresas Juniores dos seus Estados.</li><br>

                <li> Bom trabalho e seja mais uma vez bem vindo a Vitrine de EJ.</li><br>
            </p>
    </div>    
  </div>
</div>

app/views/session/index.html.erb
<%= stylesheet_link_tag "landingpage" %>
<%= render 'layouts/minimenu' %>
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1 style="font-family: Pacifico; font-size: 8em;">Vitrine</h1>
                    <h3>Encontre soluções de alta qualidade e incentive o empreendedorismo no Brasil</h3>
                    <hr class="intro-divider">
                        <div style="margin-top: 30px; margin-bottom: 30px;">                          
                            <a href="/find" class="btn btn-default"><span class="network-name">Encontrar uma Empresa Junior</span></a> OU <a href="/users/new" class="btn btn-default"><span class="network-name">Cadastrar uma Empresa Junior</span></a>
                        </div>
                        <div style="margin-top: 30px; margin-bottom: 30px;">
                            <hr class="intro-divider">
                            <h4>Você não sabe o que é uma Empresa Junior?</h4>
                            <a href="/explanation" class="btn btn-success"><span class="network-name">Saiba Mais</span></a>
                            </hr>
                        </div>
                    </hr>                                                
                </div>
            </div>
        </div>
    </div>
</div>

app/views/session/new.html.erb
<%= render 'layouts/minimenu' %>
<div class="container login-bg">
	<div class="login-form-signin">
  	<div class="login-logo"><%= image_tag("logo.png") %></div>
    <div class="login-wrap">
      <%= form_tag do %>
        <div class="form-group has-feedback lg left-feedback no-label">
          <%= text_field_tag :email, params[:email], class: "form-control", placeholder: "Email" %>
        </div>
        <div class="form-group has-feedback lg left-feedback no-label">
          <%= password_field_tag :password, params[:password], class: "form-control", placeholder: "Password" %>
        </div>

        <p><%= link_to "Esqueci a senha", recover_path %></p>

        <button type="submit" class="btn btn-lg btn-primary btn-block">Log in</button>
      <%end%>

      <form method="get" action="/users/new">
        <button class="btn btn-success btn-block">Cadastrar</button>
      </form>
    </div>    
    <div class="login-logo"><%= link_to "Feedback", "/feedback" %></div>
  </div>
</div>

<script>
  $("#email").inputmask({ alias: "email"});
</script>