config/routes.rb
Rails.application.routes.draw do
  root 'session#index'

  
  get "log_in" => "session#new", :as => "log_in"
  get "/explanation" => "session#explanation"
  post "log_in" => "session#create"
  get "log_out" => "session#destroy"
  get "/help" => "session#help"

  get "/feedback" => "feedback#feedback"
  post "/feedback" => "feedback#feedback_sent"

  get "/members/new" => "members#new", :as => "new_member"
  post "/members" => "members#create", :as => "create_member"
  get "/members" => "members#index", :as => "members"
  get "/member/:id" => "members#show", :as => "member"
  get "/members/edit/:id" => "members#edit"
  put '/member/:id' => "members#update", :as => 'update_member'
  delete '/members/delete/:id' => "members#destroy"

  get "/junior_enterprises/new" => "junior_enterprises#new", :as => "new_junior_enterprise"
  get "/messages" => "junior_enterprises#messages"
  post "/junior_enterprises" => "junior_enterprises#create", :as => "create_junior_enterprise"
  get "/junior_enterprises/edit" => "junior_enterprises#edit", :as => "edit_junior_enterprise"
  put "/junior_enterprises/:id" => "junior_enterprises#update", :as => "update_junior_enterprise"
  get "/junior_enterprises" => "junior_enterprises#index", :as => "junior_enterprises"
  get "/junior_enterprise/:id" => "junior_enterprises#show", :as => "junior_enterprise"
  get "/dashboard" => "junior_enterprises#dashboard", :as => "dashboard"
  get "/find" => "junior_enterprises#find", :as => "find"
  get "/search" => "junior_enterprises#search", :as => "search"
  get "/junior_enterprises/:id/seal" => "junior_enterprises#seal"

  get '/admin/junior_enterprises' => "junior_enterprises#index"
  get '/admin/junior_enterprises/edit/:id' => "junior_enterprises#edit"
  get '/admin/junior_enterprises/new' => "junior_enterprises#new"
  get '/admin/junior_enterprises/delete/:id' => "junior_enterprises#destroy"  
  patch "/junior_enterprise/:id" => "junior_enterprises#update"

  get '/admin/messages' => "messages#index"
  get '/admin/messages/edit/:id' => "messages#edit"
  get '/admin/messages/new' => "messages#new"
  post '/messages/:id' => "messages#create"
  post '/messages' => "messages#create"
  delete '/messages/:id' => "messages#destroy"
  get '/admin/messages/delete/:id' => "messages#destroy"  
  put "/admin/message/:id" => "messages#update", :as => "update_message"

  get '/admin/users' => "users#index", :as => 'admin_users'
  get '/admin/users/edit/:id' => "users#edit"
  get '/admin/users/new' => "users#new"
  get '/admin/users/delete/:id' => "users#destroy"

  get '/admin/members' => "members#index"
  get '/admin/members/edit/:id' => "members#edit"
  get '/admin/members/new' => "members#new"
  get '/admin/members/delete/:id' => "members#destroy"

  get '/federation/dashboard' => "junior_enterprises#search"

  get "/users/new" => "users#new", :as => "new_user"
  post "/users" => "users#create", :as => "create_user"
  get "/users" => "users#index", :as => "users"
  get "/user/:id" => "users#show", :as => "user"
  get "/recover" => "users#recover", :as => "recover"  
  post "/recover" => "users#recover_email"
  put '/users/:id' => "users#update", :as => 'update_user'

end

app/controllers/junior_enterprises_controller.rb
class JuniorEnterprisesController < ApplicationController
  before_action :number_of_messages, only: [:members, :edit, :dashboard]

  def index
    @junior_enterprises = []

    result = HTTParty.get("http://jeapi.herokuapp.com/junior_enterprises",
    :headers => { 'token' => JEAPI_KEY } )

    ActiveSupport::JSON.decode(result.body).each do |junior_enterprise|
      je = OpenStruct.new(junior_enterprise)

      @junior_enterprises << je
    end

    @junior_enterprises = Kaminari.paginate_array(@junior_enterprises).page(params[:page]).per(10)

    if is_admin?
      render template: "admin/junior_enterprise_index"
    end 
  end

  def show
    /Set @current_user if there is a user loged in/
    current_user

    @message = Message.new

    is_federation?(@current_user) ? (@access = "1") : (@access = "0")

    result_je = HTTParty.get("http://jeapi.herokuapp.com/junior_enterprises/#{params[:id]}",
    :headers => { 'token' => JEAPI_KEY, 'access' => @access } )

    @junior_enterprise = OpenStruct.new(ActiveSupport::JSON.decode(result_je.body))


    result_user = HTTParty.get("http://jeapi.herokuapp.com/users/#{@junior_enterprise.user_id}",
    :headers => { 'token' => JEAPI_KEY } )

    @user = OpenStruct.new(ActiveSupport::JSON.decode(result_user.body))

    streeAddress = @junior_enterprise.address.tr(",-/", " ")
    streeAddress = streeAddress.split.join(" ")
    streeAddress = streeAddress.tr(" ", "+")


    if ( !@junior_enterprise.state.blank? && !@junior_enterprise.city.blank? && !@junior_enterprise.address.blank?)
      @mapAddress = streeAddress + "," + @junior_enterprise.city.tr(" ", "+") + "," + @junior_enterprise.state.tr(" ", "+")
    end

    if is_federation?(@current_user)
      render template: "federation/junior_enterprise_show"
    end 
  end

  def new
    @junior_enterprise = JuniorEnterprise.new
    if is_admin?
      render template: "admin/junior_enterprise_new"
    elsif is_federation?
    end 
  end

  # GET /junior_enterprises/1/edit
  def edit
    current_user

    is_admin?(@current_user) ? (@id = params[:id]) : (@id = current_user.junior_enterprise.id)

    result = HTTParty.get("http://jeapi.herokuapp.com/junior_enterprises/#{@id}",
    :headers => { 'token' => JEAPI_KEY } )

    //
    hash = ActiveSupport::JSON.decode(result.body)
    hash.delete("messages")
    hash.delete("members")
    //

    @junior_enterprise = JuniorEnterprise.new(hash)

    if is_admin?(@current_user)
      render template: "admin/junior_enterprise_edit"
    end 
  end

  # POST /junior_enterprises
  # POST /junior_enterprises.json
  def create
    @junior_enterprise = JuniorEnterprise.new(junior_enterprise_params) 
    @junior_enterprise.save!

    is_admin? ? (@user_id = @junior_enterprise.id) : (@user_id = current_user.id) 

    result = HTTParty.post("http://jeapi.herokuapp.com/junior_enterprises",
    :body => {:name => @junior_enterprise.name, :user_id => @user_id, :logo => @junior_enterprise.logo_url.to_s , :description => @junior_enterprise.description, :phrase => @junior_enterprise.phrase, :phrase => @junior_enterprise.phrase, :site => @junior_enterprise.site, :phone => @junior_enterprise.phone, :city => @junior_enterprise.city, :state => @junior_enterprise.state, :youtube => @junior_enterprise.youtube, :facebook => @junior_enterprise.facebook, :course => @junior_enterprise.course, :area => @junior_enterprise.area, :address => @junior_enterprise.address, :consultor => @junior_enterprise.consultor, :product => @junior_enterprise.product, :access => 0, :project => @junior_enterprise.project, :training => @junior_enterprise.training},
    :headers => { 'token' => JEAPI_KEY } )
    
    @junior_enterprise.destroy
    if result.code == 201
      if is_admin? 
        redirect_to "/admin/junior_enterprises", notice: "Criado com sucesso"
      else
        redirect_to "/dashboard", notice: "Criado com sucesso"
      end
    else
      @errors = JSON.parse(result.body)
      is_admin?(@current_user) ? (render template: "admin/junior_enterprise_new") : (render :new)  
    end
  end

  def update
    current_user
    @junior_enterprise = JuniorEnterprise.new(junior_enterprise_params)
    @junior_enterprise.save!

    is_admin?(@current_user) ? @user_id = @junior_enterprise.user_id : @user_id = @current_user.id

    result = HTTParty.put("http://jeapi.herokuapp.com/junior_enterprises/#{params[:id]}",
    :body => {:name => @junior_enterprise.name, :user_id => @user_id, :logo => @junior_enterprise.logo_url.to_s , :description => @junior_enterprise.description, :phrase => @junior_enterprise.phrase, :phrase => @junior_enterprise.phrase, :site => @junior_enterprise.site, :phone => @junior_enterprise.phone, :city => @junior_enterprise.city, :state => @junior_enterprise.state, :youtube => @junior_enterprise.youtube, :facebook => @junior_enterprise.facebook, :course => @junior_enterprise.course, :area => @junior_enterprise.area, :address => @junior_enterprise.address, :consultor => @junior_enterprise.consultor, :product => @junior_enterprise.product, :access => 0, :project => @junior_enterprise.project, :training => @junior_enterprise.training },
    :headers => { 'token' => JEAPI_KEY } )
    
    @junior_enterprise.destroy
    if result.code == 204      
      if is_admin? @current_user
        redirect_to "/admin/junior_enterprises", notice: "Editado com sucesso"
      else
        redirect_to "/junior_enterprises/edit", notice: "Editado com sucesso"
      end
    else
      @errors = JSON.parse(result.body)
      is_admin?(@current_user) ? (render template: "admin/junior_enterprise_edit") : (render :edit)  
    end
  end

  # DELETE /junior_enterprises/1
  # DELETE /junior_enterprises/1.json
  def destroy
    result = HTTParty.delete("http://jeapi.herokuapp.com/junior_enterprises/#{params[:id]}",
    :headers => { 'token' => JEAPI_KEY } )

    if is_admin? 
      redirect_to "/admin/junior_enterprises", notice: "Deletado com sucesso"
    else
      redirect_to "/log_out", notice: "Deletado com sucesso"
    end
  end

  def dashboard
    current_user.junior_enterprise.nil? ? (redirect_to "/junior_enterprises/new") : ""
  end

  def find
  end

  def search
    current_user
    @je = []

    if is_federation?(@current_user)
      params[:state] = @current_user.state
    end 

    result = HTTParty.get("http://jeapi.herokuapp.com/search", 
    :body => { :name => params[:name], :state => params[:state], :area => params[:area], :consultor => params[:consultor],
              :project => params[:project], :training => params[:training], :product => params[:product] },
    :headers => { 'token' => JEAPI_KEY } )

    ActiveSupport::JSON.decode(result.body).each do |junior_enterprise|
      @je << OpenStruct.new(junior_enterprise)
    end

    @je = Kaminari.paginate_array(@je).page(params[:page]).per(10)

    if is_federation?(@current_user)
      render template: "federation/junior_enterprise_index"
    end 
  end

  def messages
    current_user
    @number_of_messages = 0

    @messages = Kaminari.paginate_array(@current_user.junior_enterprise.messages).page(params[:page]).per(10)

    result = HTTParty.put("http://jeapi.herokuapp.com/messages/read/#{@current_user.junior_enterprise.id}",
    :headers => { 'token' => JEAPI_KEY } )
  end

  def seal
    current_user
    if is_federation?(@current_user)
      result = HTTParty.post("http://jeapi.herokuapp.com/junior_enterprises/#{params[:id]}/seal",
      :headers => { 'token' => JEAPI_KEY } )

      redirect_to "/federation/dashboard"
    end 
  end

  private
    def set_junior_enterprise
      if is_admin?
        result_je = HTTParty.get("http://jeapi.herokuapp.com/junior_enterprises/#{params[:id]}",
        :headers => { 'token' => JEAPI_KEY } )

        @junior_enterprise = OpenStruct.new(ActiveSupport::JSON.decode(result_je.body))
      else
        @junior_enterprise = current_user.junior_enterprise
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def junior_enterprise_params
      params.require(:junior_enterprise).permit(:seal ,:access, :user_id,:name, :logo, :description, :phrase, :site, :phone, :city, :state, :facebook, :youtube, :course, :area, :address, :training, :consultor, :product, :project)
    end
end

app/helpers/junior_enterprises_helper.rb
module JuniorEnterprisesHelper
end

app/views/junior_enterprises/dashboard.html.erb
<%= render 'layouts/headmenu' %>
<div id="layout-container">
  <div id="main">  
      <div class="head-title"></div>
      <div class="margin-container">
        <div class="scrollable wrapper">
          <div class="row">
            <div class="col-md-12">
              <div class="page-heading">
              </div>
            </div>
          </div>
          <div class="row">
                    <div class="profile-info col-lg-9 col-lg-offset-1">                        
                        <div class="panel">
                            <div class="bio-graph-heading">
                              <h3> <%= @current_user.junior_enterprise.phrase %> </h3>
                            </div>
                            <div class="panel-body bio-graph-info">
                                <h1><%= @current_user.junior_enterprise.name %></h1>
                                <div class="row">
                                    <% unless @current_user.junior_enterprise.course.blank? %>
                                      <div class="bio-row">
                                          <p><span>Curso: </span> <%= @current_user.junior_enterprise.course %></p>
                                      </div>
                                    <% end %>
                                    <% unless @current_user.junior_enterprise.area.blank? %>
                                      <div class="bio-row">
                                          <p><span>Area: </span> <%= @current_user.junior_enterprise.area %></p>
                                      </div>
                                    <% end %>
                                    <% unless @current_user.junior_enterprise.site.blank? %>
                                      <div class="bio-row">
                                          <p><span>Site: </span> <%= @current_user.junior_enterprise.site %></p>
                                      </div>
                                    <% end %>
                                    <% unless @current_user.junior_enterprise.phone.blank? %>
                                      <div class="bio-row">
                                          <p><span>Telefone: </span> <%= @current_user.junior_enterprise.phone %></p>
                                      </div>
                                    <% end %>
                                    <% unless @current_user.junior_enterprise.youtube.blank? %>
                                      <div class="bio-row">
                                          <p><span>Youtube: </span> <%= @current_user.junior_enterprise.youtube %></p>
                                      </div>
                                    <% end %>
                                    <% unless @current_user.junior_enterprise.facebook.blank? %>
                                      <div class="bio-row">
                                          <p><span>Facebook: </span> <%= @current_user.junior_enterprise.facebook %></p>
                                      </div>
                                    <% end %>
                                    <% unless @current_user.junior_enterprise.city.blank? %>
                                      <div class="bio-row">
                                          <p><span>Cidade: </span> <%= @current_user.junior_enterprise.city %></p>
                                      </div>
                                    <% end %>
                                    <% unless @current_user.junior_enterprise.state.blank? %>
                                      <div class="bio-row">
                                          <p><span>Estado: </span> <%= @current_user.junior_enterprise.state %></p>
                                      </div>
                                    <% end %>
                                    <% unless @current_user.junior_enterprise.address.blank? %>
                                      <div class="bio-row">
                                          <p><span>Endereço: </span> <%= @current_user.junior_enterprise.address %></p>
                                      </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>   
        </div>
      </div>
    </div>
</div>
<%= messages_alert %>

app/views/junior_enterprises/edit.html.erb
<%= render 'layouts/headmenu' %>
<div id="layout-container">
  <div id="main">  
      <div class="head-title"></div>
      <div class="margin-container">
        <div class="scrollable wrapper">
  <div class="row">
    <div class="col-md-12">
    </div>
  </div>
  <div class="row">
        <div class="profile-info col-lg-9 col-lg-offset-1">                        
            <div class="panel">
              <div class="bio-graph-heading">
                <h3> Mensagens </h3>
              </div>
              <div class="panel-body bio-graph-info">
                <%= form_for @junior_enterprise, url: update_junior_enterprise_path(@junior_enterprise.id), :html => { :method => :put }  do |f| %>
                        <div id="wizard" class="swMain">
                          <div class="bio-graph-heading" style="padding: 15px;margin-left: 30px;margin-right: 30px;"> 1. Dados </div>
                          <div id="step-1" style="display: block; left: 0px;">
                            <table cellspacing="3" cellpadding="3" align="center">
                              <tbody>
                                <tr>
                                  <td align="center" colspan="3">&nbsp;</td>
                                </tr>
                                <tr>
                                  <td align="right">Nome :</td>
                                  <td align="left">
                                    <%= f.text_field :name, class: "txtBox", placeholder: "Nome"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Curso :</td>
                                  <td align="left">
                                    <%= f.text_field :course, class: "txtBox", placeholder: "Curso"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Área de Atuação :</td>
                                  <td align="left">                                    
                                    <%= select_tag('junior_enterprise[area]', options_for_select([['Em Construção']], selected: @junior_enterprise.area )) %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Tipo de Serviço:</td>
                                  <td align="left">
                                      <%= f.check_box :project, style:"margin-left:5px"%> Projetos
                                      <%= f.check_box :consultor, style:"margin-left:5px"%> Consultoria
                                      <%= f.check_box :training, style:"margin-left:5px"%> Treinamento
                                      <%= f.check_box :product, style:"margin-left:5px"%> Produtos
                                  </td>
                                </tr> 
                                <tr>
                                  <td align="right">Estado :</td>
                                  <td align="left">                                    
                                    <%= select_tag('junior_enterprise[state]', options_for_select([['Acre'],['Alagoas'], ['Amapá'], ['Amazonas'], ['Bahia'], ['Ceará'], ['Distrito Federal'], ['Espirito Santo'], ['Goiás'], ['Maranhão'], ['Mato Grosso'], ['Mato Grosso do Sul'], ['Minas Gerais'], ['Pará'], ['Paraíba'], ['Paraná'], ['Pernambuco'], ['Piauí'], ['Rio de Janeiro'], ['Rio Grande do Norte'], ['Rio Grande do Sul'], ['Rondônia'], ['Roraima'], ['Santa Catarina'], ['São Paulo'], ['Sergipe'], ['Tocantins']], selected: @junior_enterprise.state )) %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Cidade :</td>
                                  <td align="left">
                                    <%= f.text_field :city, class: "txtBox", placeholder: "Cidade"  %>
                                  </td>
                                </tr>

                                <tr>
                                  <td align="right">Endereço :</td>
                                  <td align="left">
                                    <%= f.text_field :address, class: "txtBox", placeholder: "Endereço", rel: "tooltip", title: "Cuidado ao preencher o seu endereço, cheque no Google Maps se há algum resultado."  %>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                          <br>

                          <div class="bio-graph-heading" style="padding: 15px;margin-left: 30px;margin-right: 30px;"> 2. Detalhes </div>
                          <div id="step-1" style="display: block; left: 0px;">
                            <table cellspacing="3" cellpadding="3" align="center">
                              <tbody>
                                <tr>
                                  <td align="center" colspan="3">&nbsp;</td>
                                </tr>
                                <tr>
                                  <td align="right">Slogan :</td>
                                  <td align="left">
                                    <%= f.text_area :phrase, class: "form-control", placeholder: "Frase"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Descrição :</td>
                                  <td align="left">
                                    <%= f.text_area :description, class: "form-control", placeholder: "Descrição"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Telefone :</td>
                                  <td align="left">
                                    <%= f.text_field :phone, class: "txtBox", placeholder: "Telefone"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Site :</td>
                                  <td align="left">
                                    <%= f.text_field :site, class: "txtBox", placeholder: "Site"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Facebook :</td>
                                  <td align="left">
                                    <%= f.text_field :facebook, class: "txtBox", placeholder: "Facebook"  %>
                                  </td>
                                </tr>
                                <tr>
                                  <td align="right">Youtube :</td>
                                  <td align="left">
                                    <%= f.text_field :youtube, class: "txtBox", placeholder: "Youtube"  %>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                          <br>

                          
                          <div class="bio-graph-heading" style="padding: 15px;margin-left: 30px;margin-right: 30px;"> 3. Arquivos </div>
                          <div id="step-1" style="display: block; left: 0px;">
                            <table cellspacing="3" cellpadding="3" align="center">
                              <tbody>
                                <tr>
                                  <td align="center" colspan="3">&nbsp;</td>
                                </tr>
                                <tr>
                                  <td align="right">Logo :</td> 
                                  <td align="left" id="logo" rel="tooltip" title="Use imagens com resolução com no máximo 120x120 e evite usar fundo transparente.">  
                                    <%= f.file_field :logo, class: "txtBox" %>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                          <br>

                          <div class="stepContainer" style="height: 179px;"></div>
                          <div class="actionBar">
                            <button type="submit"  class="buttonFinish">Atualizar</button>
                          </div>
                        </div>
                        <% end %> 
              </div>
            </div>
        </div>
    </div>   
</div>
      </div>
    </div>
</div>
<script>
$(function(){
  $("#junior_enterprise_address[rel='tooltip']").tooltip();
  $("#logo[rel='tooltip']").tooltip();
  $("#junior_enterprise_email").inputmask({ alias: "email"});
  $("#junior_enterprise_phone").inputmask("(99)9999-9999");
})
</script>

app/views/junior_enterprises/find.html.erb
<%= render 'layouts/minimenu' %>
<div id="layout-container">
  <div id="main" style="left:   0px !important;">  
    <div class="head-title">
  <div class="row">
    <div class="col-md-12">
    </div>
  </div>
</div>
  <div class="margin-container">
    <div class="scrollable wrapper">
      <div class="row">
        <div class="col-md-12">
          <div class="page-heading">
          </div>
        </div>
      </div>
      <div class="row">
              <div class="profile-info col-lg-9 col-lg-offset-1">                  
                  <div class="panel">
                      <div class="bio-graph-heading">
                        <h1>Encontre a Empresa Junior que irá solucionar os seus problemas<h1>
                      </div>
                      <div class="panel-body bio-graph-info">
                          <div class="row">
                              <%= form_tag search_path, :method => 'get' do %>
                              <p>
                                <h5><strong>Você sabe o nome da Empresa Junior?</strong><h5>
                                <div class="form-group has-feedback lg left-feedback no-label">
                                  <%= text_field_tag "name", params[:name], class: "form-control", placeholder: "Nome", style: "width: 30%; margin-left: 1%;" %>
                                </div>
                              </p>
                              <p>
                                <h5><strong>Em que área você precisa de apoio?</strong><h5>
                                <div class="form-group has-feedback lg left-feedback no-label">
                                  <%= select_tag "area", "<option>Ainda em Construção</option>".html_safe, class: 'form-control', include_blank: true , style: "width: 30%; margin-left: 1%;"%>
                                </div>
                              </p>
                              <p>
                                <h5><strong>Qual o seu estado?</strong><h5>
                                <div class="form-group has-feedback lg left-feedback no-label">
                                  <%= select_tag "state", "<option></option><option>Acre</option><option>Alagoas</option><option>Amapá</option><option>Amazonas</option><option>Bahia</option><option>Ceará</option><option>Distrito Federal</option><option>Espirito Santo</option><option>Goiás</option><option>Maranhão</option><option>Mato Grosso</option><option>Mato Grosso do Sul</option><option>Minas Gerais</option><option>Pará</option><option>Paraíba</option><option>Paraná</option><option>Pernambuco</option><option>Piauí</option><option>Rio de Janeiro</option><option>Rio Grande do Norte</option><option>Rio Grande do Sul</option><option>Rondônia</option><option>Roraima</option><option>Santa Catarina</option><option>São Paulo</option><option>Sergipe</option><option>Tocantins</option>".html_safe, class: 'form-control', style: "width: 30%; margin-left: 1%;" %>
                                </div>
                              </p>
                              <p>
                                <h5><strong>Quais dos seguintes serviços você busca?</strong><h5>
                              </p>
                              <p>
                                <div class="form-group has-feedback lg left-feedback no-label">

                                  <label class="checkbox-inline">                                    
                                    <%= check_box_tag 'consultor', true, false%>Consultoria
                                  </label><br>
                                  <label class="checkbox-inline">                                    
                                    <%= check_box_tag 'project', true, false%>Projetos
                                  </label><br>
                                  <label class="checkbox-inline">                                    
                                    <%= check_box_tag 'training', true, false%>Treinamento
                                  </label><br>
                                  <label class="checkbox-inline">                                    
                                    <%= check_box_tag 'product', true, false, style:"margin-left=-10px !important;"%>Produtos
                                  </label><br>
                              </p>
                              <button type="submit" class="btn btn-success" style="margin-top: 15px;">Buscar</button>
                            <%end%>
                          </div>
                      </div>
                  </div>
              </div>
          </div>   
        </div>
      </div>
    </div>
</div>